name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write   # нужно для создания PR/коммитов

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black isort
      - name: Run linters
        run: |
          ruff check .
          black --check .
          isort --check-only .
      - name: Run tests
        run: pytest -q

permissions:
  contents: write

jobs:
  auto-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install formatters
        run: pip install black ruff isort
      - name: Run formatters (may change files)
        id: format
        run: |
          black .
          ruff format .
          isort .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "style: apply automatic formatting (black / ruff / isort)"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Create PR with formatting changes
        if: steps.format.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "style: apply automatic formatting (black / ruff / isort)"
          branch: auto/formatting
          title: "Automatic formatting: black / ruff / isort"
          body: "This PR applies automatic code formatting."

