name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linters
        run: |
          ruff check .
          black --check .
          isort --check-only .
      - name: Run tests
        run: pytest -q

  auto-format:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    if: github.event_name == 'push' # можно менять: запускать только по schedule или на demand
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install formatters
        run: pip install black ruff isort
      - name: Run formatters
        run: |
          black .
          ruff format .
          isort .
      - name: Commit and create PR if changes
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "style: apply automatic formatting (black / ruff / isort)"
          branch: auto/formatting
          title: "Automatic formatting: black / ruff / isort"
          body: "This PR applies automatic code formatting."
